services:
  - type: web
    name: sanjivni
    runtime: python

    buildCommand: "./build.sh"

    startCommand: "gunicorn config.wsgi:application"

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings