# Generated by Django 6.0.7 on 2026-07-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Powder', 'Powder'), ('Tea', 'Tea'), ('Capsules', 'Capsules'), ('Oil', 'Oil')], default='Powder', max_length=20),
        ),
    ]
