# Generated by Django 6.0.7 on 2026-07-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
    ]
